version: '3.8'

services:
  jeen-insights-api:
    build: .
    container_name: jeen-insights-api
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./db:/app/db
      - ./templates:/app/templates
    networks:
      - jeen-insights-network

  jeen-insights-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: jeen-insights-ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://jeen-insights-api:8000
      - UI_PORT=8501
    depends_on:
      - jeen-insights-api
    volumes:
      - ./src:/app/src
    networks:
      - jeen-insights-network

networks:
  jeen-insights-network:
    driver: bridge
